# Tests heartbeat_listener and heartbeat_sender in the same container using a local Redis server
image: python:3.7.3

pipelines:
  default:
    - step:
        caches:
          - pip
        script: # Test
          - apt-get update && apt-get -y install libgirepository1.0-dev
          - pip install -r requirements.txt
          - apt-get update && apt-get -y install redis-server
          - nohup redis-server &
          - bash tests/fake_pipe_reader &
          - ln -s tests/heartbeat_listener.yaml heartbeat_listener.yaml
          - ln -s tests/heartbeat_sender.yaml heartbeat_sender.yaml
          - python3 heartbeat_sender.py &
          - python3 heartbeat_listener.py &
          - sleep 60s
          - pkill redis-server
          - ls -l /tmp/received5
